<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260403144733 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category (id INT AUTO_INCREMENT NOT NULL, project_id INT NOT NULL, user_id INT NOT NULL, name VARCHAR(128) NOT NULL, status INT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('DROP TABLE mantis_api_token_table');
        $this->addSql('DROP TABLE mantis_bugnote_table');
        $this->addSql('DROP TABLE mantis_bugnote_text_table');
        $this->addSql('DROP TABLE mantis_bug_file_table');
        $this->addSql('DROP TABLE mantis_bug_history_table');
        $this->addSql('DROP TABLE mantis_bug_monitor_table');
        $this->addSql('DROP TABLE mantis_bug_relationship_table');
        $this->addSql('DROP TABLE mantis_bug_revision_table');
        $this->addSql('DROP TABLE mantis_bug_tag_table');
        $this->addSql('DROP TABLE mantis_bug_text_table');
        $this->addSql('DROP TABLE mantis_category_table');
        $this->addSql('DROP TABLE mantis_config_table');
        $this->addSql('DROP TABLE mantis_custom_field_project_table');
        $this->addSql('DROP TABLE mantis_custom_field_string_table');
        $this->addSql('DROP TABLE mantis_custom_field_table');
        $this->addSql('DROP TABLE mantis_email_table');
        $this->addSql('DROP TABLE mantis_filters_table');
        $this->addSql('DROP TABLE mantis_news_table');
        $this->addSql('DROP TABLE mantis_plugin_table');
        $this->addSql('DROP TABLE mantis_project_file_table');
        $this->addSql('DROP TABLE mantis_project_hierarchy_table');
        $this->addSql('DROP TABLE mantis_project_user_list_table');
        $this->addSql('DROP TABLE mantis_project_version_table');
        $this->addSql('DROP TABLE mantis_sponsorship_table');
        $this->addSql('DROP TABLE mantis_tag_table');
        $this->addSql('DROP TABLE mantis_tokens_table');
        $this->addSql('DROP TABLE mantis_user_pref_table');
        $this->addSql('DROP TABLE mantis_user_print_pref_table');
        $this->addSql('DROP TABLE mantis_user_profile_table');
        $this->addSql('DROP INDEX idx_bug_status ON mantis_bug_table');
        $this->addSql('DROP INDEX idx_bug_sponsorship_total ON mantis_bug_table');
        $this->addSql('DROP INDEX idx_bug_fixed_in_version ON mantis_bug_table');
        $this->addSql('ALTER TABLE mantis_bug_table DROP projection, DROP os, DROP os_build, DROP platform, DROP version, DROP fixed_in_version, DROP build, DROP profile_id, DROP view_state, DROP sponsorship_total, DROP sticky, DROP target_version, DROP category_id, DROP due_date, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE project_id project_id INT DEFAULT NULL, CHANGE reporter_id reporter_id INT NOT NULL, CHANGE handler_id handler_id INT NOT NULL, CHANGE duplicate_id duplicate_id INT NOT NULL, CHANGE priority priority INT NOT NULL, CHANGE severity severity INT NOT NULL, CHANGE reproducibility reproducibility INT NOT NULL, CHANGE status status INT NOT NULL, CHANGE resolution resolution INT NOT NULL, CHANGE eta eta INT NOT NULL, CHANGE bug_text_id bug_text_id INT NOT NULL, CHANGE summary summary VARCHAR(255) NOT NULL, CHANGE date_submitted date_submitted INT DEFAULT NULL, CHANGE last_updated last_updated INT DEFAULT NULL');
        $this->addSql('ALTER TABLE mantis_bug_table ADD CONSTRAINT FK_95BDEF51166D1F9C FOREIGN KEY (project_id) REFERENCES mantis_project_table (id)');
        $this->addSql('ALTER TABLE mantis_bug_table ADD CONSTRAINT FK_95BDEF51E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES mantis_user_table (id)');
        $this->addSql('ALTER TABLE mantis_bug_table ADD CONSTRAINT FK_95BDEF51A6E82043 FOREIGN KEY (handler_id) REFERENCES mantis_user_table (id)');
        $this->addSql('CREATE INDEX IDX_95BDEF51E1CFE6F5 ON mantis_bug_table (reporter_id)');
        $this->addSql('CREATE INDEX IDX_95BDEF51A6E82043 ON mantis_bug_table (handler_id)');
        $this->addSql('ALTER TABLE mantis_bug_table RENAME INDEX idx_project TO IDX_95BDEF51166D1F9C');
        $this->addSql('DROP INDEX idx_project_name ON mantis_project_table');
        $this->addSql('DROP INDEX idx_project_view ON mantis_project_table');
        $this->addSql('ALTER TABLE mantis_project_table DROP inherit_global, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(129) NOT NULL, CHANGE status status VARCHAR(6) NOT NULL, CHANGE enabled enabled VARCHAR(4) NOT NULL, CHANGE view_state view_state VARCHAR(255) DEFAULT NULL, CHANGE access_min access_min VARCHAR(255) DEFAULT NULL, CHANGE file_path file_path VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE category_id category_id INT DEFAULT NULL');
        $this->addSql('DROP INDEX idx_access ON mantis_user_table');
        $this->addSql('DROP INDEX idx_user_cookie_string ON mantis_user_table');
        $this->addSql('DROP INDEX idx_email ON mantis_user_table');
        $this->addSql('DROP INDEX idx_enable ON mantis_user_table');
        $this->addSql('ALTER TABLE mantis_user_table DROP login_count, DROP lost_password_request_count, DROP failed_login_count, DROP cookie_string, DROP last_visit, DROP date_created, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE username username VARCHAR(180) NOT NULL, CHANGE realname realname VARCHAR(191) NOT NULL, CHANGE email email VARCHAR(191) NOT NULL, CHANGE password password VARCHAR(255) NOT NULL, CHANGE enabled enabled INT NOT NULL, CHANGE protected protected INT NOT NULL, CHANGE access_level access_level INT NOT NULL');
        $this->addSql('ALTER TABLE mantis_user_table RENAME INDEX idx_user_username TO UNIQ_IDENTIFIER_USERNAME');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE mantis_api_token_table (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED DEFAULT 0 NOT NULL, name VARCHAR(128) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, hash VARCHAR(128) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, date_created INT UNSIGNED DEFAULT 1 NOT NULL, date_used INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX idx_user_id_name (user_id, name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_bugnote_table (id INT UNSIGNED AUTO_INCREMENT NOT NULL, bug_id INT UNSIGNED DEFAULT 0 NOT NULL, reporter_id INT UNSIGNED DEFAULT 0 NOT NULL, bugnote_text_id INT UNSIGNED DEFAULT 0 NOT NULL, view_state SMALLINT DEFAULT 10 NOT NULL, note_type INT DEFAULT 0, note_attr VARCHAR(250) CHARACTER SET utf8mb3 DEFAULT \'\' COLLATE `utf8mb3_general_ci`, time_tracking INT UNSIGNED DEFAULT 0 NOT NULL, last_modified INT UNSIGNED DEFAULT 1 NOT NULL, date_submitted INT UNSIGNED DEFAULT 1 NOT NULL, INDEX idx_bug (bug_id), INDEX idx_last_mod (last_modified), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_bugnote_text_table (id INT UNSIGNED AUTO_INCREMENT NOT NULL, note LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_bug_file_table (id INT UNSIGNED AUTO_INCREMENT NOT NULL, bug_id INT UNSIGNED DEFAULT 0 NOT NULL, title VARCHAR(250) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, description VARCHAR(250) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, diskfile VARCHAR(250) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, filename VARCHAR(250) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, folder VARCHAR(250) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, filesize INT DEFAULT 0 NOT NULL, file_type VARCHAR(250) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, content LONGBLOB DEFAULT NULL, date_added INT UNSIGNED DEFAULT 1 NOT NULL, user_id INT UNSIGNED DEFAULT 0 NOT NULL, bugnote_id INT UNSIGNED DEFAULT 0, INDEX idx_diskfile (diskfile), INDEX idx_bug_file_bug_id (bug_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_bug_history_table (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED DEFAULT 0 NOT NULL, bug_id INT UNSIGNED DEFAULT 0 NOT NULL, field_name VARCHAR(64) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, old_value VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, new_value VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, type SMALLINT DEFAULT 0 NOT NULL, date_modified INT UNSIGNED DEFAULT 1 NOT NULL, INDEX idx_history_user_id (user_id), INDEX idx_bug_history_date_modified (date_modified), INDEX idx_bug_history_bug_id (bug_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_bug_monitor_table (user_id INT UNSIGNED DEFAULT 0 NOT NULL, bug_id INT UNSIGNED DEFAULT 0 NOT NULL, INDEX idx_bug_id (bug_id), PRIMARY KEY (user_id, bug_id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_bug_relationship_table (id INT UNSIGNED AUTO_INCREMENT NOT NULL, source_bug_id INT UNSIGNED DEFAULT 0 NOT NULL, destination_bug_id INT UNSIGNED DEFAULT 0 NOT NULL, relationship_type SMALLINT DEFAULT 0 NOT NULL, INDEX idx_relationship_destination (destination_bug_id), INDEX idx_relationship_source (source_bug_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_bug_revision_table (id INT UNSIGNED AUTO_INCREMENT NOT NULL, bug_id INT UNSIGNED NOT NULL, bugnote_id INT UNSIGNED DEFAULT 0 NOT NULL, user_id INT UNSIGNED NOT NULL, type INT UNSIGNED NOT NULL, value LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, timestamp INT UNSIGNED DEFAULT 1 NOT NULL, INDEX idx_bug_rev_type (type), INDEX idx_bug_rev_id_time (bug_id, timestamp), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_bug_tag_table (bug_id INT UNSIGNED DEFAULT 0 NOT NULL, tag_id INT UNSIGNED DEFAULT 0 NOT NULL, user_id INT UNSIGNED DEFAULT 0 NOT NULL, date_attached INT UNSIGNED DEFAULT 1 NOT NULL, INDEX idx_bug_tag_tag_id (tag_id), PRIMARY KEY (bug_id, tag_id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_bug_text_table (id INT UNSIGNED AUTO_INCREMENT NOT NULL, description LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, steps_to_reproduce LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, additional_information LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_category_table (id INT UNSIGNED AUTO_INCREMENT NOT NULL, project_id INT UNSIGNED DEFAULT 0 NOT NULL, user_id INT UNSIGNED DEFAULT 0 NOT NULL, name VARCHAR(128) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, status INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX idx_category_project_name (project_id, name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_config_table (config_id VARCHAR(64) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, project_id INT DEFAULT 0 NOT NULL, user_id INT DEFAULT 0 NOT NULL, access_reqd INT DEFAULT 0, type INT DEFAULT 90, value LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, PRIMARY KEY (config_id, project_id, user_id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_custom_field_project_table (field_id INT DEFAULT 0 NOT NULL, project_id INT UNSIGNED DEFAULT 0 NOT NULL, sequence SMALLINT DEFAULT 0 NOT NULL, PRIMARY KEY (field_id, project_id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_custom_field_string_table (field_id INT DEFAULT 0 NOT NULL, bug_id INT DEFAULT 0 NOT NULL, value VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, text LONGTEXT CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_general_ci`, INDEX idx_custom_field_bug (bug_id), PRIMARY KEY (field_id, bug_id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_custom_field_table (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(64) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, type SMALLINT DEFAULT 0 NOT NULL, possible_values TEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, default_value VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, valid_regexp VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, access_level_r SMALLINT DEFAULT 0 NOT NULL, access_level_rw SMALLINT DEFAULT 0 NOT NULL, length_min INT DEFAULT 0 NOT NULL, length_max INT DEFAULT 0 NOT NULL, require_report TINYINT DEFAULT 0 NOT NULL, require_update TINYINT DEFAULT 0 NOT NULL, display_report TINYINT DEFAULT 0 NOT NULL, display_update TINYINT DEFAULT 1 NOT NULL, require_resolved TINYINT DEFAULT 0 NOT NULL, display_resolved TINYINT DEFAULT 0 NOT NULL, display_closed TINYINT DEFAULT 0 NOT NULL, require_closed TINYINT DEFAULT 0 NOT NULL, filter_by TINYINT DEFAULT 1 NOT NULL, INDEX idx_custom_field_name (name), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_email_table (email_id INT UNSIGNED AUTO_INCREMENT NOT NULL, email VARCHAR(191) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, subject VARCHAR(250) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, metadata LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, body LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, submitted INT UNSIGNED DEFAULT 1 NOT NULL, PRIMARY KEY (email_id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_filters_table (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT DEFAULT 0 NOT NULL, project_id INT DEFAULT 0 NOT NULL, is_public TINYINT DEFAULT NULL, name VARCHAR(64) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, filter_string LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_news_table (id INT UNSIGNED AUTO_INCREMENT NOT NULL, project_id INT UNSIGNED DEFAULT 0 NOT NULL, poster_id INT UNSIGNED DEFAULT 0 NOT NULL, view_state SMALLINT DEFAULT 10 NOT NULL, announcement TINYINT DEFAULT 0 NOT NULL, headline VARCHAR(64) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, body LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, last_modified INT UNSIGNED DEFAULT 1 NOT NULL, date_posted INT UNSIGNED DEFAULT 1 NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_plugin_table (basename VARCHAR(40) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, enabled TINYINT DEFAULT 0 NOT NULL, protected TINYINT DEFAULT 0 NOT NULL, priority INT UNSIGNED DEFAULT 3 NOT NULL, PRIMARY KEY (basename)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_project_file_table (id INT UNSIGNED AUTO_INCREMENT NOT NULL, project_id INT UNSIGNED DEFAULT 0 NOT NULL, title VARCHAR(250) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, description VARCHAR(250) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, diskfile VARCHAR(250) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, filename VARCHAR(250) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, folder VARCHAR(250) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, filesize INT DEFAULT 0 NOT NULL, file_type VARCHAR(250) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, content LONGBLOB DEFAULT NULL, date_added INT UNSIGNED DEFAULT 1 NOT NULL, user_id INT UNSIGNED DEFAULT 0 NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_project_hierarchy_table (child_id INT UNSIGNED NOT NULL, parent_id INT UNSIGNED NOT NULL, inherit_parent TINYINT DEFAULT 0 NOT NULL, INDEX idx_project_hierarchy_parent_id (parent_id), UNIQUE INDEX idx_project_hierarchy (child_id, parent_id), INDEX idx_project_hierarchy_child_id (child_id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_project_user_list_table (project_id INT UNSIGNED DEFAULT 0 NOT NULL, user_id INT UNSIGNED DEFAULT 0 NOT NULL, access_level SMALLINT DEFAULT 10 NOT NULL, INDEX idx_project_user (user_id), PRIMARY KEY (project_id, user_id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_project_version_table (id INT AUTO_INCREMENT NOT NULL, project_id INT UNSIGNED DEFAULT 0 NOT NULL, version VARCHAR(64) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, description LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, released TINYINT DEFAULT 1 NOT NULL, obsolete TINYINT DEFAULT 0 NOT NULL, date_order INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX idx_project_version (project_id, version), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_sponsorship_table (id INT AUTO_INCREMENT NOT NULL, bug_id INT DEFAULT 0 NOT NULL, user_id INT DEFAULT 0 NOT NULL, amount INT DEFAULT 0 NOT NULL, logo VARCHAR(128) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, url VARCHAR(128) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, paid TINYINT DEFAULT 0 NOT NULL, date_submitted INT UNSIGNED DEFAULT 1 NOT NULL, last_updated INT UNSIGNED DEFAULT 1 NOT NULL, INDEX idx_sponsorship_bug_id (bug_id), INDEX idx_sponsorship_user_id (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_tag_table (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED DEFAULT 0 NOT NULL, name VARCHAR(100) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, description LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, date_created INT UNSIGNED DEFAULT 1 NOT NULL, date_updated INT UNSIGNED DEFAULT 1 NOT NULL, INDEX idx_tag_name (name), PRIMARY KEY (id, name)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_tokens_table (id INT AUTO_INCREMENT NOT NULL, owner INT NOT NULL, type INT NOT NULL, value LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, timestamp INT UNSIGNED DEFAULT 1 NOT NULL, expiry INT UNSIGNED DEFAULT 1 NOT NULL, INDEX idx_typeowner (type, owner), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_user_pref_table (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED DEFAULT 0 NOT NULL, project_id INT UNSIGNED DEFAULT 0 NOT NULL, default_profile INT UNSIGNED DEFAULT 0 NOT NULL, default_project INT UNSIGNED DEFAULT 0 NOT NULL, refresh_delay INT DEFAULT 0 NOT NULL, redirect_delay INT DEFAULT 0 NOT NULL, bugnote_order VARCHAR(4) CHARACTER SET utf8mb3 DEFAULT \'ASC\' NOT NULL COLLATE `utf8mb3_general_ci`, email_on_new TINYINT DEFAULT 0 NOT NULL, email_on_assigned TINYINT DEFAULT 0 NOT NULL, email_on_feedback TINYINT DEFAULT 0 NOT NULL, email_on_resolved TINYINT DEFAULT 0 NOT NULL, email_on_closed TINYINT DEFAULT 0 NOT NULL, email_on_reopened TINYINT DEFAULT 0 NOT NULL, email_on_bugnote TINYINT DEFAULT 0 NOT NULL, email_on_status TINYINT DEFAULT 0 NOT NULL, email_on_priority TINYINT DEFAULT 0 NOT NULL, email_on_priority_min_severity SMALLINT DEFAULT 10 NOT NULL, email_on_status_min_severity SMALLINT DEFAULT 10 NOT NULL, email_on_bugnote_min_severity SMALLINT DEFAULT 10 NOT NULL, email_on_reopened_min_severity SMALLINT DEFAULT 10 NOT NULL, email_on_closed_min_severity SMALLINT DEFAULT 10 NOT NULL, email_on_resolved_min_severity SMALLINT DEFAULT 10 NOT NULL, email_on_feedback_min_severity SMALLINT DEFAULT 10 NOT NULL, email_on_assigned_min_severity SMALLINT DEFAULT 10 NOT NULL, email_on_new_min_severity SMALLINT DEFAULT 10 NOT NULL, email_bugnote_limit SMALLINT DEFAULT 0 NOT NULL, language VARCHAR(32) CHARACTER SET utf8mb3 DEFAULT \'english\' NOT NULL COLLATE `utf8mb3_general_ci`, timezone VARCHAR(32) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_user_print_pref_table (user_id INT UNSIGNED DEFAULT 0 NOT NULL, print_pref VARCHAR(64) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, PRIMARY KEY (user_id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mantis_user_profile_table (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED DEFAULT 0 NOT NULL, platform VARCHAR(32) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, os VARCHAR(32) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, os_build VARCHAR(32) CHARACTER SET utf8mb3 DEFAULT \'\' NOT NULL COLLATE `utf8mb3_general_ci`, description LONGTEXT CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_general_ci`, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('DROP TABLE category');
        $this->addSql('ALTER TABLE mantis_bug_table DROP FOREIGN KEY FK_95BDEF51166D1F9C');
        $this->addSql('ALTER TABLE mantis_bug_table DROP FOREIGN KEY FK_95BDEF51E1CFE6F5');
        $this->addSql('ALTER TABLE mantis_bug_table DROP FOREIGN KEY FK_95BDEF51A6E82043');
        $this->addSql('DROP INDEX IDX_95BDEF51E1CFE6F5 ON mantis_bug_table');
        $this->addSql('DROP INDEX IDX_95BDEF51A6E82043 ON mantis_bug_table');
        $this->addSql('ALTER TABLE mantis_bug_table ADD projection SMALLINT DEFAULT 10 NOT NULL, ADD os VARCHAR(32) DEFAULT \'\' NOT NULL, ADD os_build VARCHAR(32) DEFAULT \'\' NOT NULL, ADD platform VARCHAR(32) DEFAULT \'\' NOT NULL, ADD version VARCHAR(64) DEFAULT \'\' NOT NULL, ADD fixed_in_version VARCHAR(64) DEFAULT \'\' NOT NULL, ADD build VARCHAR(32) DEFAULT \'\' NOT NULL, ADD profile_id INT UNSIGNED DEFAULT 0 NOT NULL, ADD view_state SMALLINT DEFAULT 10 NOT NULL, ADD sponsorship_total INT DEFAULT 0 NOT NULL, ADD sticky TINYINT DEFAULT 0 NOT NULL, ADD target_version VARCHAR(64) DEFAULT \'\' NOT NULL, ADD category_id INT UNSIGNED DEFAULT 1 NOT NULL, ADD due_date INT UNSIGNED DEFAULT 1 NOT NULL, CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE project_id project_id INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE reporter_id reporter_id INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE handler_id handler_id INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE duplicate_id duplicate_id INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE priority priority SMALLINT DEFAULT 30 NOT NULL, CHANGE last_updated last_updated INT UNSIGNED DEFAULT 1 NOT NULL, CHANGE date_submitted date_submitted INT UNSIGNED DEFAULT 1 NOT NULL, CHANGE severity severity SMALLINT DEFAULT 50 NOT NULL, CHANGE reproducibility reproducibility SMALLINT DEFAULT 10 NOT NULL, CHANGE status status SMALLINT DEFAULT 10 NOT NULL, CHANGE resolution resolution SMALLINT DEFAULT 10 NOT NULL, CHANGE eta eta SMALLINT DEFAULT 10 NOT NULL, CHANGE bug_text_id bug_text_id INT UNSIGNED DEFAULT 0 NOT NULL, CHANGE summary summary VARCHAR(128) DEFAULT \'\' NOT NULL');
        $this->addSql('CREATE INDEX idx_bug_status ON mantis_bug_table (status)');
        $this->addSql('CREATE INDEX idx_bug_sponsorship_total ON mantis_bug_table (sponsorship_total)');
        $this->addSql('CREATE INDEX idx_bug_fixed_in_version ON mantis_bug_table (fixed_in_version)');
        $this->addSql('ALTER TABLE mantis_bug_table RENAME INDEX idx_95bdef51166d1f9c TO idx_project');
        $this->addSql('ALTER TABLE mantis_project_table ADD inherit_global TINYINT DEFAULT 0 NOT NULL, CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(128) DEFAULT \'\' NOT NULL, CHANGE status status SMALLINT DEFAULT 10 NOT NULL, CHANGE enabled enabled TINYINT DEFAULT 1 NOT NULL, CHANGE view_state view_state SMALLINT DEFAULT 10 NOT NULL, CHANGE access_min access_min SMALLINT DEFAULT 10 NOT NULL, CHANGE file_path file_path VARCHAR(250) DEFAULT \'\' NOT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE category_id category_id INT UNSIGNED DEFAULT 1 NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX idx_project_name ON mantis_project_table (name)');
        $this->addSql('CREATE INDEX idx_project_view ON mantis_project_table (view_state)');
        $this->addSql('ALTER TABLE mantis_user_table ADD login_count INT DEFAULT 0 NOT NULL, ADD lost_password_request_count SMALLINT DEFAULT 0 NOT NULL, ADD failed_login_count SMALLINT DEFAULT 0 NOT NULL, ADD cookie_string VARCHAR(64) DEFAULT \'\' NOT NULL, ADD last_visit INT UNSIGNED DEFAULT 1 NOT NULL, ADD date_created INT UNSIGNED DEFAULT 1 NOT NULL, CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE username username VARCHAR(191) DEFAULT \'\' NOT NULL, CHANGE realname realname VARCHAR(191) DEFAULT \'\' NOT NULL, CHANGE email email VARCHAR(191) DEFAULT \'\' NOT NULL, CHANGE enabled enabled TINYINT DEFAULT 1 NOT NULL, CHANGE protected protected TINYINT DEFAULT 0 NOT NULL, CHANGE access_level access_level SMALLINT DEFAULT 10 NOT NULL, CHANGE password password VARCHAR(64) DEFAULT \'\' NOT NULL');
        $this->addSql('CREATE INDEX idx_access ON mantis_user_table (access_level)');
        $this->addSql('CREATE UNIQUE INDEX idx_user_cookie_string ON mantis_user_table (cookie_string)');
        $this->addSql('CREATE INDEX idx_email ON mantis_user_table (email)');
        $this->addSql('CREATE INDEX idx_enable ON mantis_user_table (enabled)');
        $this->addSql('ALTER TABLE mantis_user_table RENAME INDEX uniq_identifier_username TO idx_user_username');
    }
}
